# Generated by Django 3.2.15 on 2024-05-12 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время запроса')),
            ],
            options={
                'unique_together': {('lon', 'lat')},
            },
        ),
    ]
