FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /usr/src/app/templates
COPY ./frontend/templates ./
WORKDIR /usr/src/app
RUN apt-get update || : && apt-get install python3 python3-pip -y && rm -rf /var/lib/apt/lists/*
COPY ./backend .env requirements.txt ./
RUN pip3 install -r requirements.txt
EXPOSE 8000
CMD ["sh", "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"] 