services:
  pg_db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: "${PG_USER:-admin}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:-123}"
      POSTGRES_DB: "${PG_DB:-starburger_db}"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d starburger_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - media:/usr/src/app/backend/media
    environment:
      SECRET_KEY: "${SECRET_KEY:-secret_key}"
      DEBUG: "${DEBUG:-true}"
      DATABASE_URL: "${POSTGRESQL_DB_URL:-postgres://admin:123@localhost:5432/starburger_db}"
      YANDEX_API_KEY: "${YANDEX_API_KEY:-yandex_api_key}"
    ports:
      - 80:8000
    depends_on:
      pg_db:
        condition: service_healthy
    command: ["sh", "-c", "pip3 install -r ../requirements.txt && python3 manage.py collectstatic --no-input && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"]

volumes:
  db_data:
  media:
