# Generated by Django 3.2.15 on 2024-05-04 14:24

from django.db import migrations


def set_orderproduct_price(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    order_products = OrderProduct.objects.all()
    for order_product in order_products.iterator():
        if not order_product.price:
            order_product.price = order_product.product.price
            order_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderproduct_price'),
    ]

    operations = [
        migrations.RunPython(set_orderproduct_price),
    ]
