# Generated by Django 3.2.15 on 2024-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к заказу', verbose_name='Комментарий'),
        ),
    ]
