# Generated by Django 3.2.15 on 2024-05-05 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20240505_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('online', 'Онлайн на сайте'), ('card', 'Картой курьеру'), ('cash', 'Наличными курьеру')], db_index=True, default='online', max_length=100, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, verbose_name='Время звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Зарегестрирован'),
        ),
    ]
