# Generated by Django 3.2.15 on 2024-05-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20240511_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodcartapp.restaurant', verbose_name='Где будет готовиться'),
        ),
    ]
