# Generated by Django 3.2.15 on 2024-05-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocode', '0001_initial'),
        ('foodcartapp', '0051_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='geo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='geocode.geocode'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='geo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='geocode.geocode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1_manager', 'Обработка заказа'), ('2_cooking', 'Приготовление заказа'), ('3_delivery', 'Доставка заказа'), ('4_ready', 'Готово')], db_index=True, max_length=100, verbose_name='Статус заказа'),
        ),
    ]
