# Generated by Django 3.2.15 on 2024-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20240505_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1_manager', 'Обработка заказа'), ('2_coocking', 'Приготовление заказа'), ('3_delivery', 'Доставка заказа'), ('4_ready', 'Готово')], db_index=True, max_length=100, verbose_name='Статус заказа'),
        ),
    ]
