# Generated by Django 3.2.15 on 2024-08-30 21:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20240512_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='registrated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Зарегестрирован'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
